/*The sequence of triangle numbers is generated by adding the natural numbers.So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be :

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers :

1 : 1
3 : 1, 3
6 : 1, 2, 3, 6
10 : 1, 2, 5, 10
15 : 1, 3, 5, 15
21 : 1, 3, 7, 21
28 : 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors ?*/
#include <iostream>
#include<vector>
#include<cmath>
#define ll long long
using namespace std;
ll countDiv(ll a)
{
	ll ct=0;
	for (ll k = 1;k<sqrt(a);k++)
	{
		if (a % k == 0)
			ct=ct+2;
		if (k * k == a)
			ct++;
	}
	//cout << ct << " ";
	return ct;
}

int main() {
	ll n=sqrt(LLONG_MAX);
	ll m,p;
	cin >> m;
	 for (ll i = 1; i <=n; i++)
	 {
		 p = (i) * (i + 1) / 2;
		 if (p < n)
		 {
			 if (countDiv(p) > m)
			 {
				 cout << p;
				 break;
			 }
		 }
		 else break;
	 }
	return 0;
}